image:
  repository: felixdvrt/production-devops-pipeline
  tag: 06c2f78
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

serviceAccount:
  enabled: false

httpRoute:
  enabled: false

autoscaling:
  enabled: false

replicaCount: 3