image:
  repository: felixdvrt/production-devops-pipeline
  tag: 5bebb82
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

serviceAccount:
  enabled: false

httpRoute:
  enabled: false

autoscaling:
  enabled: false